---
title: "Target Date"
output: html_notebook
---

### Load libraries
```{r}
library(readr)
library(ggplot2)
library(dplyr)
library(lubridate)
library(tidyr)
library(readxl)
library(magrittr)
library(xlsx)
```

### Load datasets

```{r}
umsatz <- read_csv("Daten/umsatzdaten_gekuerzt.csv", 
    col_types = cols(Datum = col_date(format = "%Y-%m-%d")))
umsatz <- umsatz %>% mutate(Datum = as.Date(umsatz$Datum))


kiwo <- read_csv("Daten/kiwo.csv", col_types = cols(Datum = col_date(format = "%Y-%m-%d")))
kiwo <- kiwo %>% mutate(Datum = as.Date(kiwo$Datum))

wetter <- read_csv("Daten/wetter.csv")
wetter <- wetter %>% mutate(Datum = as.Date(wetter$Datum))

wetter <- wetter %>% 
  mutate(WindFct = cut(Windgeschwindigkeit, 
                       breaks = c(0, 5, 10, 20, 28, max(Windgeschwindigkeit)), 
                       labels = c("leicht bis schwach", "maessig bis frisch", "stark bis stuermisch", "Sturm", "Orkan"), 
                       include.lowest = T, right = F))

wetter <- wetter %>% 
  mutate(BewoelkungFct = cut(Bewoelkung, 
                       breaks = c(0, 1, 3, 7, 8), 
                       labels = c("nicht bewoelkt", "heiter", "stark bewoelkt", "bedeckt"), 
                       include.lowest = T, right=F))

wetter <- wetter %>% 
  mutate(TemperaturFct = cut(Temperatur, 
                       breaks = c(-10, 1, 15, 24, 30, 40), 
                       labels = c("Eistag", "Kalttag", "Warmtag", "Sommertag", "Hitzetag"), 
                       include.lowest = T, right=F))

wetter <- wetter %>% 
  mutate(WettercodeFct = cut(Wettercode, 
                       breaks = c(0, 49, 59, 69, 79, 90, 99), 
                       labels = c("Keine Form von Niederschlag", "Spruehregen", "Regen", "Schnee", "Schauer", "Gewitter"), 
                       include.lowest = T, right=F))


arbeitslosigkeit <- read_delim("Daten/Arbeitslosigkeit.csv", 
    ";", escape_double = FALSE, col_types = cols(Datum = col_date(format = "%d.%m.%Y")), 
    trim_ws = TRUE) 
arbeitslosigkeit <- arbeitslosigkeit %>% mutate(Datum = as.Date(arbeitslosigkeit$Datum))


semesterferien <- read_excel("Daten/CAU_Semesterferien.xlsx", 
    col_types = c("date", "numeric"))
semesterferien <- semesterferien %>% mutate(Datum = as.Date(semesterferien$Datum))


datumsangaben <- read_delim("Daten/Date.csv", ";", escape_double = FALSE, 
    col_types = cols(Datum = col_date(format = "%d.%m.%Y")), 
    trim_ws = TRUE)
datumsangaben <- datumsangaben %>% mutate(Datum = as.Date(datumsangaben$Datum))


digitale_woche <- read_excel("Daten/Digitale_Woche.xlsx", 
    col_types = c("date", "numeric"))
digitale_woche <- digitale_woche %>% mutate(Datum = as.Date(digitale_woche$Datum))


feiertage <- read_excel("Daten/feiertage.xlsx", col_types = c("text", "date", "numeric","numeric", "numeric", "text"))
feiertage <- feiertage %>% mutate(Datum = as.Date(feiertage$Datum))


jahreszeitenbeginn <- read_excel("Daten/Jahreszeitenbeginn.xlsx", 
    col_types = c("date", "numeric", "text"))
jahreszeitenbeginn <- jahreszeitenbeginn %>% mutate(Datum = as.Date(jahreszeitenbeginn$Datum))


jahreszeiten <- read_excel("Daten/Meteorologische Jahreszeiten.xlsx", 
    col_types = c("date", "numeric", "numeric", 
        "numeric", "numeric"))
jahreszeiten <- jahreszeiten %>% mutate(Datum = as.Date(jahreszeiten$Datum))


bevoelkerung <- read_excel("Daten/Population_Kiel.xlsx", 
    col_types = c("date", "numeric"))
bevoelkerung <- bevoelkerung %>% mutate(Datum = as.Date(bevoelkerung$Datum))

schulferien <- read_excel("Daten/Schulferien.xlsx", 
    col_types = c("date", "numeric"))
schulferien <- schulferien %>% mutate(Datum = as.Date(schulferien$Datum))


temperaturdifferenz <- read_excel("Daten/Temperaturdifferenz_und_Durchschnitt.xlsx", 
    col_types = c("date", "numeric", "numeric", 
        "numeric", "numeric", "numeric"))
temperaturdifferenz <- temperaturdifferenz %>% mutate(Datum = as.Date(temperaturdifferenz$Datum))


tourismus <- read_excel("Daten/Tourismus.xlsx", 
    col_types = c("date", "numeric", "numeric", 
        "numeric", "numeric", "text"))
tourismus <- tourismus[,-6]
tourismus <- tourismus %>% mutate(Datum = as.Date(tourismus$Datum))


wahlen <- read_excel("Daten/Wahlen.xlsx", col_types = c("date", 
    "numeric", "text"))
wahlen <- wahlen %>% mutate(Datum = as.Date(wahlen$Datum))


weihnachtsmarkt <- read_excel("Daten/Weihnachtsmarkt.xlsx", 
    col_types = c("date", "numeric"))
weihnachtsmarkt <- weihnachtsmarkt %>% mutate(Datum = as.Date(weihnachtsmarkt$Datum))


zeitumstellung <- read_excel("Daten/Zeitumstellung.xlsx", 
    col_types = c("date", "numeric", "text"))
zeitumstellung <- zeitumstellung %>% mutate(Datum = as.Date(zeitumstellung$Datum))
```

###  Ad target date
```{r}
umsatz <- rbind(umsatz, c("2019-06-01", 1, NA))
umsatz <- rbind(umsatz, c("2019-06-01", 2, NA))
umsatz <- rbind(umsatz, c("2019-06-01", 3, NA))
umsatz <- rbind(umsatz, c("2019-06-01", 4, NA))
umsatz <- rbind(umsatz, c("2019-06-01", 5, NA))
umsatz <- rbind(umsatz, c("2019-06-01", 6, NA))

```

### Create new Umsatz varaibles (e.g turnover one week ago, two weeks ago, one year ago )
```{r}


# Create a variable  called 'preday_turnover'that includes the turnover one day ago

umsatz <- umsatz %>% mutate(preday_turnover = NA)
empty_list <- vector(mode = "list", length = 6)

for ( j in 1:6) {
   empty_list[[j]] <- umsatz %>% filter(Warengruppe == j)
     for (i in 2: nrow(empty_list[[j]])) {
          day <- empty_list[[j]][i,]$Datum
          preday <- (day -1)
         if (sum(empty_list[[j]]$Datum == preday) != 0){
         empty_list[[j]][empty_list[[j]]$Datum == day,  ]$preday_turnover <- empty_list[[j]][empty_list[[j]]$Datum == preday, ]$Umsatz 
       } else {empty_list[[j]][empty_list[[j]]$Datum == day,  ]$preday_turnover <- NA}
     }
  }

umsatz <- rbind(empty_list[[1]], empty_list[[2]], empty_list[[3]], empty_list[[4]], empty_list[[5]], empty_list[[6]])



# Create a variable  called 'preweek_turnover_1'that includes the turnover one week ago

umsatz <- umsatz %>% mutate(preweek_turnover_1 = NA)
empty_list <- vector(mode = "list", length = 6)

for ( j in 1:6) {
  empty_list[[j]] <- umsatz %>% filter(Warengruppe == j)
    for (i in 2: nrow(empty_list[[j]])) {
    day <- empty_list[[j]][i,]$Datum
    preweek <- (day -7)
       if (sum(empty_list[[j]]$Datum == preweek) != 0){
      empty_list[[j]][empty_list[[j]]$Datum == day,  ]$preweek_turnover_1 <- empty_list[[j]][empty_list[[j]]$Datum == preweek, ]$Umsatz 
    } else {empty_list[[j]][empty_list[[j]]$Datum == day,  ]$preweek_turnover_1 <- NA}
  }
}

umsatz <- rbind(empty_list[[1]], empty_list[[2]], empty_list[[3]], empty_list[[4]], empty_list[[5]], empty_list[[6]])




# Create a variable  called 'preweek_turnover_2'that includes the turnover two weeks ago

umsatz <- umsatz %>% mutate(preweek_turnover_2 = NA)
empty_list <- vector(mode = "list", length = 6)

for ( j in 1:6) {
  empty_list[[j]] <- umsatz %>% filter(Warengruppe == j)
    for (i in 2: nrow(empty_list[[j]])) {
        day <- empty_list[[j]][i,]$Datum
        preweek_2 <- (day -14)
         if (sum(empty_list[[j]]$Datum == preweek_2) != 0){
         empty_list[[j]][empty_list[[j]]$Datum == day,  ]$preweek_turnover_2 <- empty_list[[j]][empty_list[[j]]$Datum == preweek_2, ]$Umsatz 
     } else {empty_list[[j]][empty_list[[j]]$Datum == day,  ]$preweek_turnover_2 <- NA}
  }
}

umsatz <- rbind(empty_list[[1]], empty_list[[2]], empty_list[[3]], empty_list[[4]], empty_list[[5]], empty_list[[6]])





# Create a variable  called 'preyear_turnover'that includes the turnover one year ago


umsatz <- umsatz %>% mutate(preyear_turnover = NA)
empty_list <- vector(mode = "list", length = 6)

for ( j in 1:6) {
  empty_list[[j]] <- umsatz %>% filter(Warengruppe == j)
   for (i in 2: nrow(empty_list[[j]])) {
    day <- empty_list[[j]][i,]$Datum
    preyear <- (day -365)
     if (sum(empty_list[[j]]$Datum == preyear) != 0){
      empty_list[[j]][empty_list[[j]]$Datum == day,  ]$preyear_turnover <- empty_list[[j]][empty_list[[j]]$Datum == preyear, ]$Umsatz 
    } else {empty_list[[j]][empty_list[[j]]$Datum == day,  ]$preyear_turnover <- NA}
  }
}

umsatz <- rbind(empty_list[[1]], empty_list[[2]], empty_list[[3]], empty_list[[4]], empty_list[[5]], empty_list[[6]])

```


###  Select target date
```{r}
umsatz <- umsatz %>% filter(Datum == "2019-06-01")

```


### Join datasets by Datum 

```{r}

target <- left_join(umsatz, datumsangaben, by = "Datum")

target <- left_join(target,kiwo,  by = "Datum")
target <- left_join(target, weihnachtsmarkt, by = "Datum")
target <- left_join(target, wahlen, by = "Datum")
target <- left_join(target,digitale_woche,  by = "Datum")

target <- left_join(target,feiertage, by = "Datum")
target <- left_join(target, schulferien, by = "Datum")
target <- left_join(target,semesterferien,  by = "Datum")

target <- left_join(target,wetter, by = "Datum")
target <- left_join(target, temperaturdifferenz, by = "Datum")

target <- left_join(target, jahreszeitenbeginn, by = "Datum")
target <- left_join(target, jahreszeiten, by = "Datum")
target <- left_join(target, zeitumstellung, by = "Datum")


target <- left_join(target, tourismus, by = "Datum")
target <- left_join(target,arbeitslosigkeit, by = "Datum")
target <- left_join(target, bevoelkerung, by = "Datum")



```

### Adjust the joined Dataset

```{r}
# remove duplicate rows
target <- target %>% distinct()

# Set missing names
names(target)[names(target) == 'Kommentar.y'] <- 'Zeit'

# Replace some na values with 0 
target$Kieler_Woche[is.na(target$Kieler_Woche)] = 0 
target$Semesterferien[is.na(target$Semesterferien)] = 0
target$Digitale_Woche[is.na(target$Digitale_Woche)] = 0
target$Neue_Jahreszeit[is.na(target$Neue_Jahreszeit)] = 0
target$Winter[is.na(target$Winter)] = 0
target$Fruehling[is.na(target$Fruehling)] = 0
target$Sommer[is.na(target$Sommer)] = 0
target$Herbst[is.na(target$Herbst)] = 0
target$Schulferien[is.na(target$Schulferien)] = 0
target$Ankuenfte[is.na(target$Ankuenfte)] = 0
target$Uebernachtungen[is.na(target$Uebernachtungen)] = 0
target$Wahl[is.na(target$Wahl)] = 0
target$Weihnachtsmarkt[is.na(target$Weihnachtsmarkt)] = 0
target$Feiertagsart[is.na(target$Feiertagsart)] = 0
target$Gesetzl_Feiertag[is.na(target$Gesetzl_Feiertag)] = 0
target$Brueckentag[is.na(target$Brueckentag)] = 0
target$Langes_Wochenende[is.na(target$Langes_Wochenende)] = 0
target$Wahltyp[is.na(target$Wahltyp)] = 0 

# delete columns you don't need
target <- target[,-c( 23, 40, 48, 50)]
```



```{r}
# Show data
View(target)

# save data into an csv or xlsx file

write_csv(target,"Dataset_target.csv")
```


