---
title: "R Notebook"
output: html_notebook
---

```{r}
###load libraries###
##
library(readr)
library(ggplot2)
library(dplyr)
library(lubridate)
library(tidyr)
library(readxl)

###load dataset###
total <- read_excel("Dataset_total.xlsx")


### Datentypenn ändern:
total <- total %>% mutate(Temperatur = as.numeric(total$Temperatur))
total <- total %>% mutate(wochentag = as.factor(total$wochentag))
total <- total %>% mutate(monat = as.factor(total$monat))
total <- total %>% mutate(Warengruppe = as.factor(total$Warengruppe))
total <- total %>% mutate(Kieler_Woche = as.factor(total$Kieler_Woche))
total <- total %>% mutate(Bewoelkung = as.factor(total$Bewoelkung))
total <- total %>% mutate(Windgeschwindigkeit = as.factor(total$Windgeschwindigkeit))
total <- total %>% mutate(Wettercode = as.factor(total$Wettercode))
total <- total %>% mutate(Semesterferien = as.factor(total$Semesterferien))
total <- total %>% mutate(Year = as.factor(total$Year))
total <- total %>% mutate(Day_of_year = as.factor(total$Day_of_year))
total <- total %>% mutate(Week_in_year = as.factor(total$Week_in_year))
total <- total %>% mutate(Day_of_month = as.factor(total$Day_of_month))
total <- total %>% mutate(Digitale_Woche = as.factor(total$Digitale_Woche))
total <- total %>% mutate(Feiertagsart = as.factor(total$Feiertagsart))
total <- total %>% mutate(Gesetzl_Feiertag = as.factor(total$Gesetzl_Feiertag))
total <- total %>% mutate(Brueckentag = as.factor(total$Brueckentag))
total <- total %>% mutate(Langes_Wochenende = as.factor(total$Langes_Wochenende))
total <- total %>% mutate(Neue_Jahreszeit = as.factor(total$Neue_Jahreszeit))
total <- total %>% mutate(Winter = as.factor(total$Winter))
total <- total %>% mutate(Fruehling = as.factor(total$Fruehling))
total <- total %>% mutate(Sommer = as.factor(total$Sommer))
total <- total %>% mutate(Herbst = as.factor(total$Herbst))
total <- total %>% mutate(Waermer_als_normal = as.factor(total$Waermer_als_normal))
total <- total %>% mutate(Kaelter_als_normal = as.factor(total$Kaelter_als_normal))
total <- total %>% mutate(Wahl = as.factor(total$Wahl))
total <- total %>% mutate(Weihnachtsmarkt = as.factor(total$Weihnachtsmarkt))
total <- total %>% mutate(Schulferien = as.factor(total$Schulferien))
total <- total %>% mutate(Sommerzeit = as.factor(total$Sommerzeit))

###Plotten der Variablen die Signifikant sind###
plot_coeffs <- function(lm_total) {
      coeffs <- coefficients(lm_total)
      mp <- barplot(coeffs, col="#3F97D0", xaxt='n', main="Regression Coefficients")
      lablist <- names(coeffs)
      text(mp, par("usr")[3], labels = lablist, srt = 45, adj = c(1.1,1.1), xpd = TRUE, cex=0.6)
}

plot_coeffs(lm_total)


###Generalisierte Lineare Regression mit weiteren Variablen aus Create Dataset###
###Lineare Regression kann mit 0 u. 1 nichts anfangen. Generalisierte Lm beachtet neben Normalverteilung auch Binomial und Poisson###
lm_total <- glm(data = total, 
                Umsatz~preday_turnover + preweek_turnover_1 + preweek_turnover_2 + preyear_turnover + Year + Week_in_year + Day_of_year + Day_of_month + Weekday + Month + Kieler_Woche + Weihnachtsmarkt + Wahl + Wahltyp + Digitale_Woche + Feiertagsart + Schulferien + Bewoelkung + Temperatur + Windgeschwindigkeit + Wettercode + WindFct + BewoelkungFct + TemperaturFct + WettercodeFct + Durchschnittstemperatur_monatlich + Tagestemperatur_tatsaechlich + Waermer_als_normal + Kaelter_als_normal + Neue_Jahreszeit + Winter + Fruehling + Sommer + Herbst + Sommerzeit + Zeit + Ankuenfte + Uebernachtungen + Arbeitslose + Einwohnerzahl_Kiel)
                  
summary(lm_total)

###Ermittlung des R² --> 0,86 = 88%
with(summary(lm_total), 1 - deviance/null.deviance)

###Zusammenfassung welche Variablen alle Signifikant sind###
require(broom)    
lm_total_tidy = tidy(lm_total)
lm_total_tidy[lm_total_tidy$p.value < 0.05,]

###normale lm --> R²: 87% ###
lm_total <- lm(data = total, 
                Umsatz~preday_turnover + preweek_turnover_1 + preweek_turnover_2 + preyear_turnover + Year + Week_in_year + Day_of_year + Day_of_month + Weekday + Month + Kieler_Woche + Weihnachtsmarkt + Wahl + Wahltyp + Digitale_Woche + Feiertagsart + Schulferien + Bewoelkung + Temperatur + Windgeschwindigkeit + Wettercode + WindFct + BewoelkungFct + TemperaturFct + WettercodeFct + Durchschnittstemperatur_monatlich + Tagestemperatur_tatsaechlich + Waermer_als_normal + Kaelter_als_normal + Neue_Jahreszeit + Winter + Fruehling + Sommer + Herbst + Sommerzeit + Zeit + Ankuenfte + Uebernachtungen + Arbeitslose + Einwohnerzahl_Kiel)
                  
summary(lm_total)
