---
title: "SVM"
output: html_notebook
---


###Load libraries
```{r}
library(readr)
library(e1071)
library(Metrics)
library(dplyr)
library(ggplot2)
library(lubridate)
library(tidyr)
library(readxl)
library(caTools)
library(rlist)
```


### load datasets
```{r}
total <- read_csv("Dataset_total.csv")

```


###Adjust the classes of the variables
```{r}

total <- total %>% mutate(Datum = as.Date(Datum))

total <- total %>% mutate(Warengruppe = as.factor(Warengruppe))
total <- total %>% mutate(Umsatz = as.numeric(Umsatz))
total <- total %>% mutate(preday_turnover = as.numeric(preday_turnover))
total <- total %>% mutate(preweek_turnover_1 = as.numeric(preweek_turnover_1))
total <- total %>% mutate(preweek_turnover_2 = as.numeric(preweek_turnover_2))
total <- total %>% mutate(preyear_turnover = as.numeric(preyear_turnover))

total <- total %>% mutate(Year = as.factor(Year))
total <- total %>% mutate(Day_of_year = as.factor(Day_of_year))
total <- total %>% mutate(Week_in_year = as.factor(Week_in_year))
total <- total %>% mutate(Day_of_month = as.factor(Day_of_month))
total <- total %>% mutate(Weekday = as.factor(Weekday))
total <- total %>% mutate(Month = as.factor(Month))

total <- total %>% mutate(Kieler_Woche = as.factor(Kieler_Woche))
total <- total %>% mutate(Weihnachtsmarkt = as.factor(Weihnachtsmarkt))
total <- total %>% mutate(Wahl = as.factor(Wahl))
total <- total %>% mutate(Wahltyp = as.factor(Wahltyp))
total <- total %>% mutate(Digitale_Woche = as.factor(Digitale_Woche))
total <- total %>% mutate(Feiertagsart = as.factor(Feiertagsart))
total <- total %>% mutate(Gesetzl_Feiertag = as.factor(Gesetzl_Feiertag))
total <- total %>% mutate(Brueckentag = as.factor(Brueckentag))
total <- total %>% mutate(Langes_Wochenende = as.factor(Langes_Wochenende))
total <- total %>% mutate(Semesterferien = as.factor(Semesterferien))
total <- total %>% mutate(Schulferien = as.factor(Schulferien))


total <- total %>% mutate(Temperatur = as.numeric(Temperatur))
total <- total %>% mutate(Bewoelkung = as.integer(Bewoelkung))
total <- total %>% mutate(Windgeschwindigkeit = as.integer(Windgeschwindigkeit))
total <- total %>% mutate(Wettercode = as.factor(Wettercode))
total <- total %>% mutate(WindFct = as.factor(WindFct))
total <- total %>% mutate(BewoelkungFct = as.factor(BewoelkungFct))
total <- total %>% mutate(WettercodeFct = as.factor(WettercodeFct))
total <- total %>% mutate(TemperaturFct   = as.factor(TemperaturFct  ))

total <- total %>% mutate(Durchschnittstemperatur_monatlich = as.numeric(Durchschnittstemperatur_monatlich))
total <- total %>% mutate(Tagestemperatur_tatsaechlich = as.numeric(Tagestemperatur_tatsaechlich))
total <- total %>% mutate(`Differenz_zum Mittel` = as.numeric(`Differenz_zum Mittel`))
total <- total %>% mutate(Kaelter_als_normal = as.factor(Kaelter_als_normal))
total <- total %>% mutate(Waermer_als_normal = as.factor(Waermer_als_normal))


total <- total %>% mutate(Neue_Jahreszeit = as.factor(Neue_Jahreszeit))
total <- total %>% mutate(Winter = as.factor(Winter))
total <- total %>% mutate(Fruehling = as.factor(Fruehling))
total <- total %>% mutate(Sommer = as.factor(Sommer))
total <- total %>% mutate(Herbst = as.factor(Herbst))
total <- total %>% mutate(Sommerzeit = as.factor(Sommerzeit))
total <- total %>% mutate(Zeit = as.factor(Zeit))

total <- total %>% mutate(Ankuenfte = as.numeric(Ankuenfte))
total <- total %>% mutate(Arbeitslose = as.numeric(Arbeitslose))
total <- total %>% mutate(Uebernachtungen = as.numeric(Uebernachtungen))
total <- total %>% mutate(Einwohnerzahl_Kiel = as.numeric(Einwohnerzahl_Kiel))

```

### Delete Wettercode due to a lot of NA's
```{r}
total <- total %>% select(-c(WettercodeFct, Wettercode))

```


### Split dataset into train and test data
```{r}
total <- na.omit(total)

## 75% of the sample size
smp_size <- floor(0.75 * nrow(total))

## set the seed to make your partition reproducible
set.seed(123)
train_ind <- sample(seq_len(nrow(total)), size = smp_size)
train_dataset_total <- total[train_ind, ]
test_dataset_total <- total[-train_ind, ]

```


### Estimation of various SVM
```{r}

set.seed(123)
svm_1 <- tune(svm, Umsatz ~ Weekday + Month + preweek_turnover_1 + Semesterferien + Kieler_Woche, data=train_dataset_total, ranges=list(epsilon=seq(0.2,1,0.1),cost=2^(2:3)))

set.seed(123)
svm_2 <- tune(svm, Umsatz ~ preday_turnover + preweek_turnover_2 + preyear_turnover + Week_in_year, data=train_dataset_total, ranges=list(epsilon=seq(0.2,1,0.1),cost=2^(2:3)))

set.seed(123)
svm_3 <- tune(svm, Umsatz ~ preday_turnover + preweek_turnover_2 + preyear_turnover + Month + Schulferien, data=train_dataset_total, ranges=list(epsilon=seq(0.2,1,0.1),cost=2^(2:3)))

set.seed(123)
svm_4 <- tune(svm, Umsatz ~ preday_turnover + preweek_turnover_2 + preyear_turnover + Month + Schulferien + Semesterferien + WindFct + TemperaturFct, data=train_dataset_total, ranges=list(epsilon=seq(0.2,1,0.1),cost=2^(2:3)))

set.seed(123)
svm_5 <- tune(svm, Umsatz ~ preday_turnover + preweek_turnover_2 + preyear_turnover + Schulferien + Semesterferien + WindFct + BewoelkungFct + Waermer_als_normal, data=train_dataset_total, ranges=list(epsilon=seq(0.2,1,0.1),cost=2^(2:3)))

set.seed(123)
svm_6 <- tune(svm, Umsatz ~ preday_turnover + preweek_turnover_2 + preyear_turnover + Ankuenfte + Uebernachtungen + WindFct + BewoelkungFct + Waermer_als_normal, data=train_dataset_total, ranges=list(epsilon=seq(0.2,1,0.1),cost=2^(2:3)))

set.seed(123)
svm_7 <- tune(svm, Umsatz ~ Warengruppe + preday_turnover + preweek_turnover_1 + preweek_turnover_2 + preyear_turnover + Weekday + Year + Month + Day_of_year + Day_of_month + TemperaturFct + Semesterferien + Kieler_Woche + Feiertagsart, data=train_dataset_total, ranges=list(epsilon=seq(0.2,1,0.1),cost=2^(2:3)))

set.seed(123)
svm_8 <- tune(svm, Umsatz ~ preday_turnover + preweek_turnover_2 + preyear_turnover + Week_in_year + Warengruppe  + preweek_turnover_1 + Weekday + Year + Month + Day_of_month + TemperaturFct + Semesterferien + Kieler_Woche + Feiertagsart, data=train_dataset_total, ranges=list(epsilon=seq(0.2,1,0.1),cost=2^(2:3)))

set.seed(123)
svm_9 <- tune(svm, Umsatz ~ preday_turnover + preweek_turnover_2 + preyear_turnover + Week_in_year + preweek_turnover_1 + Warengruppe + Weekday + Year + Month + Day_of_month + Day_of_year + TemperaturFct + BewoelkungFct+ Semesterferien + Kieler_Woche + Ankuenfte + Feiertagsart, data=train_dataset_total, ranges=list(epsilon=seq(0.2,1,0.1),cost=2^(2:3)))
```



### Save SVM/ Uploade SVM 
```{r}

#list.save(svm_1, 'svm_1.rds')
#list.save(svm_2, 'svm_2.rds')
#list.save(svm_3, 'svm_3.rds')
#list.save(svm_4, 'svm_4.rds')
#list.save(svm_5, 'svm_5.rds')
#list.save(svm_6, 'svm_6.rds')
#list.save(svm_7, 'svm_7.rds')
#list.save(svm_8, 'svm_8.rds')
#list.save(svm_9, 'svm_9.rds')

svm_1 <- readRDS("./svm_1.rds")
svm_2 <- readRDS("./svm_2.rds")
svm_3 <- readRDS("./svm_3.rds")
svm_4 <- readRDS("./svm_4.rds")
svm_5 <- readRDS("./svm_5.rds")
svm_6 <- readRDS("./svm_6.rds")
svm_7 <- readRDS("./svm_7.rds")
svm_8 <- readRDS("./svm_8.rds")
svm_9 <- readRDS("./svm_9.rds")
```


### Checking the prediction Quality
```{r}

# Calculating the prediction for the training data using the best model according to the grid search

pred_train_1 <- predict(svm_1$best.model, train_dataset_total)
pred_train_2 <- predict(svm_2$best.model, train_dataset_total)
pred_train_3 <- predict(svm_3$best.model, train_dataset_total)
pred_train_4 <- predict(svm_4$best.model, train_dataset_total)
pred_train_5 <- predict(svm_5$best.model, train_dataset_total)
pred_train_6 <- predict(svm_6$best.model, train_dataset_total)
pred_train_7 <- predict(svm_7$best.model, train_dataset_total)
pred_train_8 <- predict(svm_8$best.model, train_dataset_total)
pred_train_9 <- predict(svm_9$best.model, train_dataset_total)

PredQualityTrain <- rbind(mape(train_dataset_total$Umsatz, pred_train_1),
                          mape(train_dataset_total$Umsatz, pred_train_2),
                          mape(train_dataset_total$Umsatz, pred_train_3),
                          mape(train_dataset_total$Umsatz, pred_train_4),
                          mape(train_dataset_total$Umsatz, pred_train_5),
                          mape(train_dataset_total$Umsatz, pred_train_6),
                          mape(train_dataset_total$Umsatz, pred_train_7),
                          mape(train_dataset_total$Umsatz, pred_train_8),
                          mape(train_dataset_total$Umsatz, pred_train_9))


# Calculating the prediction for the test data using the best model according to the grid search
pred_test_1 <- predict(svm_1$best.model, test_dataset_total)
pred_test_2 <- predict(svm_2$best.model, test_dataset_total)
pred_test_3 <- predict(svm_3$best.model, test_dataset_total)
pred_test_4 <- predict(svm_4$best.model, test_dataset_total)
pred_test_5 <- predict(svm_5$best.model, test_dataset_total)
pred_test_6 <- predict(svm_6$best.model, test_dataset_total)
pred_test_7 <- predict(svm_7$best.model, test_dataset_total)
pred_test_8 <- predict(svm_8$best.model, test_dataset_total)
pred_test_9 <- predict(svm_9$best.model, test_dataset_total)

PredQualityTest <-rbind(mape(test_dataset_total$Umsatz, pred_test_1),
                         mape(test_dataset_total$Umsatz, pred_test_2),
                         mape(test_dataset_total$Umsatz, pred_test_3),
                         mape(test_dataset_total$Umsatz, pred_test_4),
                         mape(test_dataset_total$Umsatz, pred_test_5),
                         mape(test_dataset_total$Umsatz, pred_test_6),
                         mape(test_dataset_total$Umsatz, pred_test_7),
                         mape(test_dataset_total$Umsatz, pred_test_8),
                         mape(test_dataset_total$Umsatz, pred_test_9)
                        )

Quality <- data.frame( c(1,2,3,4,5,6,7,8,9), PredQualityTrain, PredQualityTest)
colnames(Quality)<- c("Model", "Mape_Train", "Mape_Test")

#write_csv(Quality, "TableMapeSVM.csv")

```


### Save best model
```{r}

bestmodel <- svm_8$best.model

```

### Load testdataset for the targetdate
```{r}

Dataset_target <- read_csv("Dataset_target.csv")

Dataset_target <- Dataset_target %>% mutate(Datum = as.Date(Datum))

Dataset_target <- Dataset_target %>% mutate(Warengruppe = as.factor(Warengruppe))
Dataset_target <- Dataset_target %>% mutate(Umsatz = as.numeric(Umsatz))
Dataset_target <- Dataset_target %>% mutate(preday_turnover = as.numeric(preday_turnover))
Dataset_target <- Dataset_target %>% mutate(preweek_turnover_1 = as.numeric(preweek_turnover_1))
Dataset_target <- Dataset_target %>% mutate(preweek_turnover_2 = as.numeric(preweek_turnover_2))
Dataset_target <- Dataset_target %>% mutate(preyear_turnover = as.numeric(preyear_turnover))

Dataset_target <- Dataset_target %>% mutate(Year = as.factor(Year))
Dataset_target <- Dataset_target %>% mutate(Day_of_year = as.factor(Day_of_year))
Dataset_target <- Dataset_target %>% mutate(Week_in_year = as.factor(Week_in_year))
Dataset_target <- Dataset_target %>% mutate(Day_of_month = as.factor(Day_of_month))
Dataset_target <- Dataset_target %>% mutate(Weekday = as.factor(Weekday))
Dataset_target <- Dataset_target %>% mutate(Month = as.factor(Month))

Dataset_target <- Dataset_target %>% mutate(Kieler_Woche = as.factor(Kieler_Woche))
Dataset_target <- Dataset_target %>% mutate(Weihnachtsmarkt = as.factor(Weihnachtsmarkt))
Dataset_target <- Dataset_target %>% mutate(Wahl = as.factor(Wahl))
Dataset_target <- Dataset_target %>% mutate(Wahltyp = as.factor(Wahltyp))
Dataset_target <- Dataset_target %>% mutate(Digitale_Woche = as.factor(Digitale_Woche))
Dataset_target <- Dataset_target %>% mutate(Feiertagsart = as.factor(Feiertagsart))
Dataset_target <- Dataset_target %>% mutate(Gesetzl_Feiertag = as.factor(Gesetzl_Feiertag))
Dataset_target <- Dataset_target %>% mutate(Brueckentag = as.factor(Brueckentag))
Dataset_target <- Dataset_target %>% mutate(Langes_Wochenende = as.factor(Langes_Wochenende))
Dataset_target <- Dataset_target %>% mutate(Semesterferien = as.factor(Semesterferien))
Dataset_target <- Dataset_target %>% mutate(Schulferien = as.factor(Schulferien))


Dataset_target <- Dataset_target %>% mutate(Temperatur = as.numeric(Temperatur))
Dataset_target <- Dataset_target %>% mutate(Bewoelkung = as.integer(Bewoelkung))
Dataset_target <- Dataset_target %>% mutate(Windgeschwindigkeit = as.integer(Windgeschwindigkeit))
Dataset_target <- Dataset_target %>% mutate(Wettercode = as.factor(Wettercode))
Dataset_target <- Dataset_target %>% mutate(WindFct = as.factor(WindFct))
Dataset_target <- Dataset_target %>% mutate(BewoelkungFct = as.factor(BewoelkungFct))
Dataset_target <- Dataset_target %>% mutate(WettercodeFct = as.factor(WettercodeFct))
Dataset_target <- Dataset_target %>% mutate(TemperaturFct   = as.factor(TemperaturFct  ))

Dataset_target <- Dataset_target %>% mutate(Durchschnittstemperatur_monatlich = as.numeric(Durchschnittstemperatur_monatlich))
Dataset_target <- Dataset_target %>% mutate(Tagestemperatur_tatsaechlich = as.numeric(Tagestemperatur_tatsaechlich))
Dataset_target <- Dataset_target %>% mutate(`Differenz_zum Mittel` = as.numeric(`Differenz_zum Mittel`))
Dataset_target <- Dataset_target %>% mutate(Kaelter_als_normal = as.factor(Kaelter_als_normal))
Dataset_target <- Dataset_target %>% mutate(Waermer_als_normal = as.factor(Waermer_als_normal))


Dataset_target <- Dataset_target %>% mutate(Neue_Jahreszeit = as.factor(Neue_Jahreszeit))
Dataset_target <- Dataset_target %>% mutate(Winter = as.factor(Winter))
Dataset_target <- Dataset_target %>% mutate(Fruehling = as.factor(Fruehling))
Dataset_target <- Dataset_target %>% mutate(Sommer = as.factor(Sommer))
Dataset_target <- Dataset_target %>% mutate(Herbst = as.factor(Herbst))
Dataset_target <- Dataset_target %>% mutate(Sommerzeit = as.factor(Sommerzeit))
Dataset_target <- Dataset_target %>% mutate(Zeit = as.factor(Zeit))

Dataset_target <- Dataset_target %>% mutate(Ankuenfte = as.numeric(Ankuenfte))
Dataset_target <- Dataset_target %>% mutate(Arbeitslose = as.numeric(Arbeitslose))
Dataset_target <- Dataset_target %>% mutate(Uebernachtungen = as.numeric(Uebernachtungen))
Dataset_target <- Dataset_target %>% mutate(Einwohnerzahl_Kiel = as.numeric(Einwohnerzahl_Kiel))

Dataset_target <- Dataset_target %>% select(-c(WettercodeFct, Wettercode))

```


### Create prediction for 01.06.2019

```{r}

Dataset_target <- rbind(Dataset_target, test_dataset_total[1:100,])
pred_target <- predict(svm_8$best.model, Dataset_target) 
pred_target <- pred_target[1:6]

Prognose <- data.frame( Warengruppe = c(1,2,3,4,5,6), Umsatzprognose = pred_target)
```

