---
title: "SVM"
output: html_notebook
---



```{r}
###Load libraries###
##
library(readr)
library(e1071)
library(Metrics)
library(dplyr)
library(ggplot2)
```

```{r}
### load train- & testdatasets###
##
train_dataset_total <- read_csv("train_dataset_total.csv")
test_dataset_total <- read_csv("test_dataset_total.csv")
```

```{r}
###change variables to factor in BOTH sets###
##
train_dataset_total <- train_dataset_total %>% mutate(Warengruppe = as.factor(train_dataset_total$Warengruppe))
test_dataset_total <- test_dataset_total %>% mutate(Warengruppe = as.factor(test_dataset_total$Warengruppe))

train_dataset_total <- train_dataset_total %>% mutate(Kieler_Woche = as.factor(train_dataset_total$Kieler_Woche))
test_dataset_total <- test_dataset_total %>% mutate(Kieler_Woche = as.factor(test_dataset_total$Kieler_Woche))

train_dataset_total <- train_dataset_total %>% mutate(Weihnachtsmarkt = as.factor(train_dataset_total$Weihnachtsmarkt))
test_dataset_total <- test_dataset_total%>% mutate(Weihnachtsmarkt = as.factor(test_dataset_total$Weihnachtsmarkt))

train_dataset_total <- train_dataset_total %>% mutate(Digitale_Woche = as.factor(train_dataset_total$Digitale_Woche))
test_dataset_total <- test_dataset_total %>% mutate(Digitale_Woche = as.factor(test_dataset_total$Digitale_Woche))

train_dataset_total <- train_dataset_total %>% mutate(WindFct = as.factor(train_dataset_total$WindFct))
test_dataset_total <- test_dataset_total %>% mutate(WindFct = as.factor(test_dataset_total$WindFct))

train_dataset_total <- train_dataset_total %>% mutate(TemperaturFct = as.factor(train_dataset_total$TemperaturFct))
test_dataset_total <- test_dataset_total %>% mutate(TemperaturFct = as.factor(test_dataset_total$TemperaturFct))

train_dataset_total <- train_dataset_total %>% mutate(BewoelkungFct = as.factor(train_dataset_total$BewoelkungFct))
test_dataset_total <- test_dataset_total %>% mutate(BewoelkungFct = as.factor(test_dataset_total$BewoelkungFct))

train_dataset_total <- train_dataset_total %>% mutate(WettercodeFct = as.factor(train_dataset_total$WettercodeFct))
test_dataset_total <- test_dataset_total %>% mutate(WettercodeFct = as.factor(test_dataset_total$WettercodeFct))

train_dataset_total <- train_dataset_total %>% mutate(Schulferien = as.factor(train_dataset_total$Schulferien))
test_dataset_total <- test_dataset_total %>% mutate(Schulferien = as.factor(test_dataset_total$Schulferien))

train_dataset_total <- train_dataset_total %>% mutate(Semesterferien = as.factor(train_dataset_total$Semesterferien))
test_dataset_total <- test_dataset_total %>% mutate(Semesterferien = as.factor(test_dataset_total$Semesterferien))

train_dataset_total <- train_dataset_total %>% mutate(Winter = as.factor(train_dataset_total$Winter))
test_dataset_total <- test_dataset_total %>% mutate(Winter = as.factor(test_dataset_total$Winter))

train_dataset_total <- train_dataset_total %>% mutate(Fruehling = as.factor(train_dataset_total$Fruehling))
test_dataset_total <- test_dataset_total %>% mutate(Fruehling = as.factor(test_dataset_total$Fruehling))

train_dataset_total <- train_dataset_total %>% mutate(Sommer = as.factor(train_dataset_total$Sommer))
test_dataset_total <- test_dataset_total %>% mutate(Sommer = as.factor(test_dataset_total$Sommer))

train_dataset_total <- train_dataset_total %>% mutate(Herbst = as.factor(train_dataset_total$Herbst))
test_dataset_total <- test_dataset_total %>% mutate(Herbst = as.factor(test_dataset_total$Herbst))
```

ACHTUNG: STEFFENS BEISPIEL
```{r}
####Estimation of various SVM (each with optimized weighting parameters) using systematically varied hyper parameters (typically called 'grid search' approach) and cross validation
# the resulting object includes the optimal model in the element named 'best.model'
svm <- svm(Umsatz ~ Weekday + Month + preweek_turnover_1 + Semesterferien + Kieler_Woche, data=train_dataset_total, ranges = list(epsilon = seq(0.2,1,0.1), cost = 2^(2:3)))
```

